SELECT * FROM `SALARIOS` WHERE PROFISSÃO LIKE 'P%';


SELECT COUNT(NOME) AS QT_FUNCIOANARIOS FROM `SALARIOS` WHERE PROFISSÃO = 'PROFESSOR'; 


SELECT SUM(SALÁRIO) AS SOMASAL_PROF FROM SALARIOS WHERE PROFISSÃO = 'PROFESSOR' 


SELECT MAX(SALÁRIO) AS MAIOR_SALARIO 
FROM SALARIOS 
WHERE PROFISSÃO IN ('PROFESSOR', 'JOGADOR DE FUTEBOL') 


SELECT MAX(SALÁRIO) AS MAIOR_SALARIO 
FROM SALARIOS 
WHERE PROFISSÃO IN ('JOGADOR DE FUTEBOL', 'PROSISSIONAL DE TI','ATOR')
